version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo "Packages & Dependencies are getting installed"
      - echo "Packages have been installed"
      - echo "Storing Build Artifact to the Location"
artifacts:
  type: zip
  paths:
    - '*'

